// Inputs are independent acceptance data, never generated by the porting model.
export const cases: any[] = [];
export const ai = (p: string) => `packages/ai/src/${p}.ts`;
export const agent = (p: string) => `packages/agent/src/${p}.ts`;
export function add(batch: string, id: string, input: any) { cases.push({ batch, id, input }); }
function calls(batch: string, file: string, fn: string, vectors: any[][]) {
  vectors.forEach((args, n) => add(batch, `${fn}-${n}`, { op: "call", file, fn, args }));
}
const usage = {input:10,output:3,cacheRead:2,cacheWrite:1,totalTokens:16,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}};
export const assistant = (content: any[], stopReason = "stop") => ({ role:"assistant",api:"openai-completions",provider:"fixture",model:"fixture",content,usage,stopReason,timestamp:1 });

for(const fail of [false,true]) add("ai-foundation",`telemetry-${fail}`,{op:"telemetry",file:"packages/telemetry/src/memory.ts",fail});
for(const terminal of ["done","error"]) add("ai-foundation",`assistant-stream-${terminal}`,{op:"assistant-stream",file:ai("utils/event-stream"),message:assistant([{type:"text",text:"你好"}]),terminal});
calls("ai-utils",ai("utils/json-parse"),"parseStreamingJson",[[""],["{"],["{\"name\":\"你好"],["{\"items\":[1,2"],["{\"n\":false,\"v\":null}"]]);
calls("ai-utils",ai("utils/json-parse"),"parseJsonWithRepair",[["{\"x\":1}"],["{x:}"],["[1,2]"]]);
calls("ai-utils",ai("utils/text"),"contentText",[[""],[[{type:"text",text:"a"},{type:"thinking",thinking:"secret"},{type:"text",text:"b"}]],[[{type:"text",text:"中"},{type:"text",text:"文"}],"|"]]);
calls("ai-utils",ai("utils/estimate"),"estimateTextTokens",[[""],["abc"],["😀中文"],["a".repeat(41)]]);
calls("ai-utils",ai("utils/estimate"),"calculateContextTokens",[[usage]]);
calls("ai-utils",ai("utils/retry"),"retryDelayMs",[[{baseDelayMs:100,maxAgentDelayMs:350},1],[{baseDelayMs:100,maxAgentDelayMs:350},3],[{baseDelayMs:0,maxAgentDelayMs:0},8]]);
calls("ai-utils",ai("utils/transcript"),"getCurrentSystemPrompt",[[[{role:"system",content:"first",timestamp:1},{role:"user",content:"hi",timestamp:2},{role:"system",content:"second",timestamp:3}]], [[]]]);
calls("ai-utils",ai("utils/transcript"),"getCurrentTools",[[[{role:"system",content:"",timestamp:1,toolsAdded:[{name:"a",description:"A",parameters:{type:"object"}}]},{role:"system",content:"",timestamp:2,toolsRemoved:["a"],toolsAdded:[{name:"b",description:"B",parameters:{type:"object"}}]}]]]);
for(const args of [{n:"4"},{n:4},{n:null},{n:"nope"}]) calls("ai-utils",ai("utils/validation"),"validateToolArguments",[[{name:"echo",description:"",parameters:{type:"object",properties:{n:{type:"integer"}},required:["n"]}},{type:"toolCall",id:"c",name:"echo",arguments:args}]]);
// Stable unique ids even for repeated calls() groups.
for(const aborted of [false,true]) add("ai-auth",`credentials-${aborted}`,{op:"credentials",file:ai("auth/credential-store"),aborted});
add("ai-auth","pkce",{op:"pkce",file:ai("auth/oauth/pkce")});
for(const aborted of [false,true]) add("ai-models",`model-store-${aborted}`,{op:"model-store",file:ai("models-store"),aborted});

calls("core-contracts",agent("harness/utils/truncate"),"truncateHead",[["a\nb\nc",{maxLines:2,maxBytes:100}],["你好\n世界",{maxLines:5,maxBytes:7}],["abcdef",{maxBytes:3,maxLines:5}],["",{maxLines:2,maxBytes:10}]]);
calls("core-contracts",agent("harness/utils/truncate"),"truncateTail",[["a\nb\nc",{maxLines:2,maxBytes:100}],["你好世界",{maxLines:5,maxBytes:7}],["a\r\nb\r\n",{maxLines:2,maxBytes:100}]]);
for(const parallel of [false,true]) add("core-loop",`loop-${parallel}`,{op:"agent-loop",file:agent("agent"),parallel});
add("core-loop","state-reset",{op:"agent-state",file:agent("agent")});
add("core-session","session-lifecycle",{op:"session",file:agent("harness/session/memory")});
calls("core-compaction",agent("harness/compaction/compaction"),"shouldCompact",[[100,1000,{enabled:true,reserveTokens:200,keepRecentTokens:300}],[900,1000,{enabled:true,reserveTokens:200,keepRecentTokens:300}],[900,1000,{enabled:false,reserveTokens:200,keepRecentTokens:300}]]);
calls("core-compaction",agent("harness/compaction/compaction"),"estimateTokens",[[{role:"user",content:"hello",timestamp:1}],[assistant([{type:"thinking",thinking:"中文"},{type:"text",text:"answer"}])]]);
calls("core-compaction",agent("harness/compaction/utils"),"formatFileOperations",[[["a.txt","中.txt"],["b.txt"]],[[],[]]]);
const start={type:"run_start",lane:"main",runId:"r1",startedAt:1};
const tool={type:"tool_start",lane:"main",runId:"r1",toolCallId:"c1",toolName:"echo",args:{x:1}};
const snapshot={lane:"main",tipId:null,operation:null,transcript:[],configuration:{model:{provider:"fixture",modelId:"fixture"},thinkingLevel:"off",activeToolNames:[]},queues:{},stats:{messageCount:0,usage:{}}};
for(const [id,events] of Object.entries({
  tool:[start,tool,{...tool,args:{x:2}},{type:"tool_end",runId:"r1",toolCallId:"c1",toolName:"echo",result:{content:[{type:"text",text:"2"}]},isError:false}],
  stale:[start,{type:"operation_abort",operationId:"other"},{...tool,lane:"other"}],
  abort:[start,{type:"operation_abort",operationId:"r1"}],
  retry:[start,{type:"retry_scheduled",runId:"r1",attempt:2,maxAttempts:3,notBefore:10},{type:"retry_start",runId:"r1"}],
  deferred:[start,{type:"run_suspend",runId:"r1",deferred:{id:"d1"},poll:{notBefore:5}},{type:"run_resume",runId:"r1"}],
  terminal:[start,{type:"run_end",runId:"r1",status:"completed",fromTipId:null,tipId:"e1",endedAt:8}],
  fault:[{type:"fault"}], navigation:[{type:"navigation_end"}],
})) add("core-runtime",id,{op:"reducer",file:agent("harness/runtime/reducer"),snapshot,events});
calls("core-resources",agent("harness/prompt-templates"),"parseCommandArgs",[["a 'b c' \"d e\""],["  a   b "],["中文 \"\""],[""]]);
calls("core-resources",agent("harness/prompt-templates"),"substituteArgs",[["$1:$2:$@",["x","y"]],["$3/$1",["a"]],["$ARGUMENTS",["one","two"]]]);
calls("core-resources",agent("harness/skills"),"formatSkillInvocation",[[{name:"demo",description:"",filePath:"/skills/demo/SKILL.md",baseDir:"/skills/demo",content:"Hello"},"more"]]);
for(const tag of ["LaneBusy","InvalidLane","Closed","OperationMismatch"]) add("core-harness",tag,{op:"tagged-error",file:agent("harness/result"),tag,props:{message:"fixture error",lane:"main",operationId:"r1"}});
add("core-harness","lifecycle",{op:"harness-lifecycle",file:agent("harness/agent-harness")});

calls("tools-env",agent("harness/tools/image"),"detectSupportedImageMimeType",[[[]],[[71,73,70,56,57,97]],[[137,80,78,71,13,10,26,10]],[[0,1,2]]]);
for(const content of ["","hello\n世界\n"]) add("tools-env",`filesystem-${content.length}`,{op:"env",file:agent("harness/env/nodejs"),content});
for(const [id,input] of Object.entries({text:{text:"a\nb\nc\n",args:{path:"file.txt"}},slice:{text:"a\nb\nc\n",args:{path:"file.txt",offset:2,limit:1}},empty:{text:"",args:{path:"file.txt"}},past:{text:"a",args:{path:"file.txt",offset:3}},crlf:{text:"中\r\n文",args:{path:"file.txt"}},gif:{bytes:[71,73,70,56,57,97],args:{path:"file.txt"}},limit:{text:Array.from({length:2002},(_,n)=>String(n)).join("\n"),args:{path:"file.txt"}}})) add("tools-read",id,{op:"tool",file:agent("harness/tools/read"),fn:"createReadTool",...input});
for(const text of ["","a\n中\n"]) add("tools-write",`write-${text.length}`,{op:"tool",file:agent("harness/tools/write"),fn:"createWriteTool",text:"old",args:{path:"nested/file.txt",content:text},inspect:"nested/file.txt"});
for(const [id,input] of Object.entries({exact:{text:"one\ntwo\n",oldText:"two",newText:"TWO"},duplicate:{text:"x x",oldText:"x",newText:"z"},missing:{text:"a",oldText:"b",newText:"c"},crlf:{text:"a\r\nb\r\n",oldText:"b",newText:"B"},bom:{text:"\ufeffa\nb\n",oldText:"a",newText:"A"},unicode:{text:"你好世界",oldText:"世界",newText:"Pi"}})) add("tools-edit",id,{op:"tool",file:agent("harness/tools/edit"),fn:"createEditTool",text:input.text,args:{path:"file.txt",oldText:input.oldText,newText:input.newText},inspect:"file.txt"});
for(const command of ["printf 'hello\\n'","printf 'err\\n' >&2; exit 3","printf '中文'",":"]) add("tools-bash",`shell-${cases.length}`,{op:"tool",file:agent("harness/tools/bash"),fn:"createBashTool",text:"",args:{command}});
// Assign globally stable ids after construction to avoid duplicate table rows.
const ids=new Map<string,number>(); for(const c of cases){const k=c.batch+"/"+c.id; const n=ids.get(k)??0; ids.set(k,n+1); if(n)c.id+="-"+n;}
